(function($){$.circulate=function(el,options){var base=this,origWidth,origHeight,newWidth,origLeft,origTop;base.$el=$(el);base.$el.data("circulate",base);base.stopAnimation=function(){base.options.keepGoing=false;}
base.runAnimation=function(){if(base.options.keepGoing){origWidth=base.$el.width();origHeight=base.$el.height();origLeft=base.$el.position().left;origTop=base.$el.position().top;if(base.options.sizeAdjustment==100){newWidth=origWidth;newHeight=origHeight;halfWayWidth=origWidth;halfWayHeight=origHeight;}else{newWidth=parseInt(origWidth)*(base.options.sizeAdjustment/100);newHeight=parseInt(origHeight)*(base.options.sizeAdjustment/100);halfWayWidth=(parseInt(origWidth)+newWidth)/2;halfWayHeight=(parseInt(origHeight)+newHeight)/2;};if(base.$el.css("position")!="absolute"){base.$el.css("position","relative");}
base.$el.css("z-index",base.options.zIndexValues[0]);base.$el.animate({top:["+="+(base.options.height/2)+"px",'easeInQuad'],left:["+="+(base.options.width/2)+"px",'easeOutQuad'],width:[halfWayWidth,'linear'],height:[halfWayHeight,'linear'],opacity:1},base.options.speed,function(){base.$el.css("z-index",base.options.zIndexValues[1]);}).animate({top:["+="+(base.options.height/2)+"px",'easeOutQuad'],left:["-="+(base.options.width/2)+"px",'easeInQuad'],width:[newWidth,'linear'],height:[newHeight,'linear']},base.options.speed,function(){base.$el.css("z-index",base.options.zIndexValues[2]);}).animate({top:["-="+(base.options.height/2)+"px",'easeInQuad'],left:["-="+(base.options.width/2)+"px",'easeOutQuad'],width:[halfWayWidth,'linear'],height:[halfWayHeight,'linear']},base.options.speed,function(){base.$el.css("z-index",base.options.zIndexValues[3]);}).animate({top:["-="+(base.options.height/2)+"px",'easeOutQuad'],left:["+="+(base.options.width/2)+"px",'easeInQuad'],width:[origWidth,'linear'],height:[origHeight,'linear']},base.options.speed,function(){base.$el.css("z-index",base.options.zIndexValues[0]);if(base.options.loop===true){base.runAnimation();}});}};base.init=function(){base.options=$.extend({},$.circulate.defaultOptions,options);base.runAnimation();};base.init();};$.circulate.defaultOptions={speed:400,height:200,width:200,sizeAdjustment:100,loop:false,zIndexValues:[1,1,1,1],keepGoing:true};$.fn.circulate=function(options){if(typeof(options)==="string"){return this.each(function(){var safeGuard=$(this).data('circulate');if(safeGuard){safeGuard.stopAnimation();}});}else{return this.each(function(){(new $.circulate(this,options));});}};})(jQuery);function avatarImproveBag(){lAlert({title:'',from_url:'ajax.php?m=avatar_popup&type=improve_bag',width:410})}
function restoreEnergy(){lAlert({title:'',from_url:'ajax.php?m=avatar_energy',width:410})}
function avatarBuyLord(){lAlert({title:'',from_url:'ajax.php?m=avatar_gold',width:520,noClose:true})}
function avatarBuyEnergy(type,obj){$.ajax({type:'post',url:'ajax.php?m=avatar_energy',data:{type:type,key:energy_key||KEY},success:function(result){if(result.data.message){bOk(result.data.message);lPopupRemove();}
if(result.data.max){var prc=100*result.data.value/result.data.max;prc=prc>100?100:prc;avatar_energy_interval_stop=1;avatar_energy=result.data.value;avatar_energy_max=result.data.max;$('#avatar_buy_energy_popup .avatar_energy_now, #avatar_small_bar .energy_now, #body .energy_interactive .avatar_energy_now').html(avatar_energy);$('#avatar_buy_energy_popup .avatar_energy_max, #avatar_small_bar .energy_max, #body .energy_interactive .avatar_energy_max').html(avatar_energy_max);$('#body .fill_energy').removeClass('fill_energy').off('click').off('submit');animateBar({obj:'#avatar_big_bar .bar, .energy_interactive .bar',duration:500,percent:prc});animateBar({obj:'#avatar_small_bar .bar',duration:100});animateBar({obj:'#body .energy_interactive .bar',percent:prc,duration:500});doUpdateInfo(result.update);setTimeout(function(){avatarAnimateItem({html:'<img src="'+IMG_URL+'/images/items/energys.png" alt="" class="dblock" />',offset:$(obj).offset()});},100);setTimeout(function(){lPopupRemove();},400);}},dataType:'json'});}
function animateBarInterval(duration){if(avatar_energy_interval_stop||typeof(avatar_energy)=='undefined'||avatar_energy>=avatar_energy_max){avatar_energy_interval_stop=0;}else{var duration=duration||avatar_duration;animateBar({obj:'#avatar_small_bar .bar',duration:duration,callback:function(){avatar_energy_max=typeof(avatar_energy_max)!='undefined'?avatar_energy_max:100;avatar_energy=avatar_energy<avatar_energy_max?avatar_energy+1:avatar_energy_max;$('#avatar_small_bar .energy_now, #body .energy_interactive .avatar_energy_now').html(avatar_energy);$('#avatar_small_bar .energy_max, #body .energy_interactive .avatar_energy_max').html(avatar_energy_max);$('#avatar_small_bar .bar').css({width:0});animateBar({obj:'#avatar_big_bar .bar, #body .energy_interactive .bar',percent:(avatar_energy/avatar_energy_max)*100,duration:200});animateBarInterval();}});}}
function updateWatchPrice(obj){var price=$(obj).val();$('#watch_price').html(price*watchPrice);}
function avatarWatchInit(){$("#avatar_watch #name").click(function(){if(!chng){$("#avatar_watch #name").attr("style","color : #000000;");$("#avatar_watch #name").val("");chng=true;}});$("#avatar_watch #name_zorro").click(function(){if(!chngz){$("#avatar_watch #name_zorro").attr("style","color : #000000;");$("#avatar_watch #name_zorro").val("");chngz=true;}});$('#avatar_watch #type').on('change',function(){avatarWatchShowPrize();});$('#avatar_watch .watch_busy').on('click',function(){avatarShakeObj('#work_in_watch');});$('#body .avatar_rating_enemy_action.active').on('click',function(){$(this).parents('.avatar_rating_enemy').submit();});avatarWatchShowPrize();}
function avatarWatchShowPrize(){var t=$('#avatar_watch #type').val();if(t=='more'||t=='same'){$('#avatar_watch .win_prize').hide();$('#avatar_watch .win_prize_'+t).show();}else{$('#avatar_watch .win_prize').hide();$('#avatar_watch .win_prize_default').show();}}
function avatarWatchProcess(){$("#avatar_watch .can_disable").addClass('cmd_blocked').prop('disabled',true);$("#avatar_watch .arena_enemy").removeAttr('href');}
function avatarBindEnergyBuy(){$('#body .fill_energy').removeClass('submit_by_ajax').on('click',function(){avatarShakeObj('#top_menu .char_stat_energy');restoreEnergy();return false;});}
function avatarProfileInit(){$('#avatar_buy_energy, #avatar_buy_energy_top').off('click').on('click',function(){restoreEnergy();});$('#avatar_improve_bag').on('click',function(){avatarImproveBag();});}
function avatarCheckBusy(obj){if(location.hash=='#redirect'){setTimeout(function(){$(obj).addClass('shake');location.hash=location.hash.replace('#redirect','');},100);}}
function avatarShakeObj(obj){$(obj).removeClass('shake');setTimeout(function(){$(obj).addClass('shake');},50);}
function avatarMineInit(){avatarCheckBusy('#work_in_mine');start_timers();$('#avatar_mine .mine_busy').on('click',function(){avatarShakeObj('#work_in_mine');});}
function avatarAnimateItem(conf){var obj;var offset;if(typeof(conf.obj)!='undefined'){obj=$(conf.obj).clone();offset=$(conf.obj).offset();}else if(typeof(conf.html)!='undefined'){obj=$(conf.html);offset=typeof(conf.offset)!='undefined'?conf.offset:{left:mt_rand(0,1000),top:mt_rand(300,700)};}
var block=$('<div class="flying_item"></div>');obj.appendTo(block);block.css({left:offset.left+150,top:offset.top});block.appendTo('body');var t={};t.direction=0;t.speed=300;t.height=500;t.width=500;block.circulate({speed:t.speed,height:t.height-(t.height*t.direction),width:t.width-(t.width*t.direction)});block.children().animate({opacity:0},t.speed*1.3,function(){block.remove();});}
function avatarBuyGreen(){lPopupRemove();setTimeout(function(){if(IS_TEMP_USER){avatarRegMail();}else{lConfirm({title:cool_text_2,width:560,iframe:'buy.php',iframe_height:$(window).height()<800?540:700,scrolling:'auto',open:function(){$('#button1_2').parent().remove();$('.black_overlay').off('click');$('body').off('keyup');},cancel_title:buy_back_to_game});}},500)}
function avatarReferInit(){$('#avatar_refer_link').focus().select().on('click',function(){$('#avatar_refer_link').select()});if(typeof hasFlash()!='undefined'){$('#avatar_refer_copy').zclip({path:IMG_URL+'/css/modules/zclip/ZeroClipboard.swf',text:avatar_copy_hint,copy:function(){return $('#avatar_refer_link').val();}});}else{$('#avatar_refer_copy').remove();$('#avatar_refer_link').removeClass('w70p').addClass('w986p');}
$('#avatar_refer_subtabs .tabs .btn').on('click',function(){var rel=$(this).attr('rel');var type=$(this).data('type');avatar_refer_subtabs.click(rel);$('#avatar_refer_type [name="type"]').val(type);$('#avatar_refer_type').submit();});$('#referrer_shop .button_new').not('.cmd_blocked').on('click',function(e){e.preventDefault();$(this).closest('form').submit();var havemoney=parseInt($(this).data('havemoney'));if(havemoney){var animate_obj=$(this).closest('form').find('.item_box').clone();avatarAnimateItem({html:animate_obj,offset:$(this).closest('form').offset()});}})}
var reg_mail_timeout=0;function getQueryVariable(variable)
{var query=window.location.search.substring(1);var vars=query.split("&");for(var i=0;i<vars.length;i++){var pair=vars[i].split("=");if(pair[0]==variable){return pair[1];}}
return(false);}
$(function(){$('body').on('click','.buy_green',function(){if(intval(avatar_money_3.replace(/\./g,''))<intval($(this).data('price'))){if(!IS_TEMP_USER){avatarBuyGreen();return false;}else{avatarRegMail();return false;}}});$('body').on('submit','form.buy_green [type="submit"]',function(){if($(this).find('[name="ptype"]').val()==3&&avatar_money_3<Math.floor($(this).find('.money_green').html())){avatarBuyGreen();return false;}});if($('#char .life_perc').data('life')<2){avatarShakeObj('#char');}
if(location.hash=='#need_gold'){avatarBuyLord();}
if(getQueryVariable('inventory')==1){$('#selector_weapons').trigger('click');}
if(getQueryVariable('inventory')==2){$('#selector_potions').trigger('click');}
if(getQueryVariable('inventory')==3){$('#selector_artefacts').trigger('click');}});